import Footer from "@/components/shared/Footer";
import Header from "@/components/shared/Header";
import SmoothScroll from "@/components/shared/SmoothScroll";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SmoothScroll />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
